server:
  port: 8763
eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
        defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    #instance:
      #hostname: localhost